# Generated by Django 4.2.2 on 2023-08-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('io', models.CharField(choices=[('OUTPUT', '支出'), ('INPUT', '收入')], default='OUTPUT', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ItemKinds',
            fields=[
                ('kind', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=24)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='account',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemkinds'),
        ),
    ]
