# Generated by Django 4.2.2 on 2023-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account_itemkinds_delete_user_account_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
